/**
 * Created by Administrator on 2016/10/24.
 */
$(function(){
    $('.grzxdd_nav>li').click(function(){
        $(this).addClass('g_current').siblings().removeClass('g_current');
        $(this).parent().next().children().eq($(this).index()).show().siblings().hide();
    });
    /*注备*/
    $('.bz_Btn').click(function(){
        $('.beizhu').show();
        var maskHeight=$(document).height();
        var maskWidth=$(document).width();
        $(document.body).css("overflow","hidden");
        $(document).css("overflow","hidden");
        /*添加遮照层*/
        $('<div class="mask"></div>').appendTo($('body'));
        $('div.mask').css({
            'opacity':0.7,
            'background':'#000',
            'position':'absolute',
            'left':0,
            'top':0,
            'height':maskHeight,
            'width':maskWidth,
            'z-index':200
        });
        $('.mask').click(function(){
            $('.mask').remove();
            $('.beizhu').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
        $('.bz_btn>.bz_close').click(function(){
            $('.mask').remove();
            $('.beizhu').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
    });
    /*分派*/
    $('.fp_Btn').click(function(){
        $('.fenpai').show();
        var maskHeight=$(document).height();
        var maskWidth=$(document).width();
        $(document.body).css("overflow","hidden");
        $(document).css("overflow","hidden");
        //添加遮照层
        $('<div class="mask"></div>').appendTo($('body'));
        $('div.mask').css({
            'opacity':0.7,
            'background':'#000',
            'position':'absolute',
            'left':0,
            'top':0,
            'height':maskHeight,
            'width':maskWidth,
            'z-index':200
        });
        $('.mask').click(function(){
            $('.mask').remove();
            $('.fenpai').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
        $('.fp_close').click(function(){
            $('.mask').remove();
            $('.fenpai').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
    });
    $('.fenpai_ul>li').click(function(){
        $(this).addClass('yq_current').siblings().removeClass('yq_current');
        $(this).children('input[type="radio"]').prop('checked',true);
    });
    /*拒单*/
    $('.jd_Btn').click(function(){
        $('.judan').show();
        var maskHeight=$(document).height();
        var maskWidth=$(document).width();
        $(document.body).css("overflow","hidden");
        $(document).css("overflow","hidden");
        //添加遮照层
        $('<div class="mask"></div>').appendTo($('body'));
        $('div.mask').css({
            'opacity':0.7,
            'background':'#000',
            'position':'absolute',
            'left':0,
            'top':0,
            'height':maskHeight,
            'width':maskWidth,
            'z-index':200
        });
        $('.mask').click(function(){
            $('.mask').remove();
            $('.judan').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
        $('.jd_close').click(function(){
            $('.mask').remove();
            $('.judan').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
    });
    $('.judan_ul>li').click(function(){
        $(this).addClass('yq_current').siblings().removeClass('yq_current');
        $(this).children('input[type="radio"]').prop('checked',true);
    });
    /*护工管理*/
    /*搜索框*/
    $('.searchBtn').click(function(){
        if($('.hggl_form').is(':hidden')){
            $('.hggl_form').css('display','inline-block');
            $('.hggl_tit').hide();
        }else{
            $('.hggl_form').css('display','none');
            $('.hggl_tit').show();
        }
    });
    /*护工等级、状态*/
    $('.hggl_font1').parent().click(function(){
        var _this=$(this);
        if(!$(this).hasClass('h_col')){
            $(this).addClass('h_col').siblings().removeClass('h_col');
            $(this).parent().next().children().eq($(this).index()).show().siblings().hide();
        }else{
            $(this).removeClass('h_col');
            $(this).parent().next().children().eq($(this).index()).hide();
            $('.mask').remove();
        }
        if($(this).hasClass('h_col')){
            var maskHeight=$(document).height();
            var maskWidth=$(document).width();
            $(document.body).css("overflow","hidden");
            $(document).css("overflow","hidden");
            //添加遮照层
            $('<div class="mask"></div>').appendTo($('body'));
            $('div.mask').css({
                'opacity':0.7,
                'background':'#000',
                'position':'absolute',
                'left':0,
                'top':0,
                'height':maskHeight,
                'width':maskWidth,
                'z-index':200
            });
            $('.mask').click(function(){
                $('.mask').remove();
                _this.parent().next().children().eq(_this.index()).hide();
                _this.removeClass('h_col');
                $(document.body).css("overflow","auto");
                $(document).css("overflow","auto");
            });
            $('.hggl_font2').parent().click(function(){
                $('.mask').remove();
            });
        }
    });
    $('.hggl_font2').parent().click(function(){
        var _this=$(this);
        if(!$(this).hasClass('h_col')){
            $(this).addClass('h_col').siblings().removeClass('h_col');
            $(this).parent().next().children().eq($(this).index()).show().siblings().hide();
        }else{
            $(this).removeClass('h_col');
            $(this).parent().next().children().eq($(this).index()).hide();
            $('.mask1').remove();
        }
        if($(this).hasClass('h_col')){
            var maskHeight=$(document).height();
            var maskWidth=$(document).width();
            $(document.body).css("overflow","hidden");
            $(document).css("overflow","hidden");
            //添加遮照层
            $('<div class="mask1"></div>').appendTo($('body'));
            $('div.mask1').css({
                'opacity':0.7,
                'background':'#000',
                'position':'absolute',
                'left':0,
                'top':0,
                'height':maskHeight,
                'width':maskWidth,
                'z-index':200
            });
            $('.mask1').click(function(){
                $('.mask1').remove();
                _this.parent().next().children().eq(_this.index()).hide();
                _this.removeClass('h_col');
                $(document.body).css("overflow","auto");
                $(document).css("overflow","auto");
            });
            $('.hggl_font1').parent().click(function(){
                $('.mask1').remove();
            });
        }
    });
    $('.hggl_sel_ul1>li').click(function(){
        $(this).parents('.hggl_sel_con').prev().find('.hggl_font1').text($(this).children('.hggl_font').text());
        $(this).parents('.hggl_sel_con').prev().find('.hggl_font1').parent().removeClass('h_col');
        $(this).parents('.hggl_sel_con').prev().find('.hggl_font1').parent().addClass('f_col');
        $(this).parent().hide();
        $('.mask').remove();
        $('.mask1').remove();
    });
    $('.hggl_sel_ul2>li').click(function(){
        $(this).parents('.hggl_sel_con').prev().find('.hggl_font2').text($(this).children('.hggl_font').text());
        $(this).parents('.hggl_sel_con').prev().find('.hggl_font2').parent().removeClass('h_col');
        $(this).parents('.hggl_sel_con').prev().find('.hggl_font2').parent().addClass('f_col');
        $(this).parent().hide();
        $('.mask').remove();
        $('.mask1').remove();
    });
    /*更多*/
    $('.hggl_more').click(function(){
        if(!$(this).hasClass('f_col')){
            $(this).addClass('f_col');
            $(this).parent().next().children('li:nth-child(2)~li').show();
        }else{
            $(this).removeClass('f_col');
            $(this).parent().next().children('li:nth-child(2)~li').hide();
        }
    });
    /*添加护工*/
    //性别选择
    $('.addhg_sel>input[type="checkbox"]').click(function(){
        if($(this).prop('checked')==true){
            $(this).siblings('img:nth-of-type(1)').hide();
            $(this).siblings('img:nth-of-type(2)').show();
            $(this).siblings('i').addClass('f_col3').parent().siblings('.addhg_sel').children('i').removeClass('f_col3');
            $(this).parent().siblings().children('input[type="checkbox"]').prop('checked',false);
            $(this).parent().siblings().children('img:nth-of-type(1)').show();
            $(this).parent().siblings().children('img:nth-of-type(2)').hide();
        }else{
            $(this).siblings('img:nth-of-type(1)').show();
            $(this).siblings('img:nth-of-type(2)').hide();
            $(this).siblings('i').removeClass('f_col3');
        }
    });
    //上传证件
    $('.addhg_forward_sc').click(function(){
        $(this).prev('input').click();
    });
    $('.addhg_con_zj').click(function(){
        $(this).next('input[type="file"]').click();
    });
    /*等级*/
    $('.addhg_dj').click(function(){
        $('.dengji').show();
        var maskHeight=$(document).height();
        var maskWidth=$(document).width();
        $(document.body).css("overflow","hidden");
        $(document).css("overflow","hidden");
        //添加遮照层
        $('<div class="mask"></div>').appendTo($('body'));
        $('div.mask').css({
            'opacity':0.7,
            'background':'#000',
            'position':'absolute',
            'left':0,
            'top':0,
            'height':maskHeight,
            'width':maskWidth,
            'z-index':1002
        });
        $('.mask').click(function(){
            $('.mask').remove();
            $('.dengji').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
        $('.dj_close').click(function(){
            $('.mask').remove();
            $('.dengji').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
    });
    $('.dengji_ul>li').click(function(){
        $(this).addClass('yq_current').siblings().removeClass('yq_current');
        $(this).children('input[type="radio"]').prop('checked',true);
    });
    /*服务时间*/
    $('.addhg_fwsj>input[type="checkbox"]').click(function(){
        if($(this).prop('checked')==true){
            $(this).siblings('img:nth-of-type(1)').hide();
            $(this).siblings('img:nth-of-type(2)').show();
            $(this).parent().addClass('sel_current');
            $(this).siblings('i').addClass('f_col3');
        }else{
            $(this).siblings('img:nth-of-type(1)').show();
            $(this).siblings('img:nth-of-type(2)').hide();
            $(this).parent().removeClass('sel_current');
            $(this).siblings('i').removeClass('f_col3');
        }
    });
    /*服务时间弹框*/
    $('.addhg_time,.fwsj_font1').click(function(){
        $('.fuwushijian').show();
        var maskHeight=$(document).height();
        var maskWidth=$(document).width();
        $(document.body).css("overflow","hidden");
        $(document).css("overflow","hidden");
        //添加遮照层
        $('<div class="mask"></div>').appendTo($('body'));
        $('div.mask').css({
            'opacity':0.7,
            'background':'#000',
            'position':'absolute',
            'left':0,
            'top':0,
            'height':maskHeight,
            'width':maskWidth,
            'z-index':1002
        });
        $('.mask').click(function(){
            $('.mask').remove();
            $('.fuwushijian').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
        $('.fwsj_close').click(function(){
            $('.mask').remove();
            $('.fuwushijian').hide();
            $(document.body).css("overflow","auto");
            $(document).css("overflow","auto");
        });
    });
    /*服务时间弹框全选的*/
    $('.fwsj_allTime>input').click(function(){
        if($(this).prop('checked')==true){
            $(this).parents('.fuwushijian').find('.time-check').prop('checked',true);
            $(this).parents('.fuwushijian').find('.time-check').siblings('img:nth-of-type(1)').hide();
            $(this).parents('.fuwushijian').find('.time-check').siblings('img:nth-of-type(2)').show();
            $(this).siblings('i').addClass('f_col3');
            $(this).parents('.fuwushijian').find('.time-check').siblings('i').addClass('f_col3');
        }else{
            $(this).parents('.fuwushijian').find('.time-check').prop('checked',false);
            $(this).parents('.fuwushijian').find('.time-check').siblings('img:nth-of-type(1)').show();
            $(this).parents('.fuwushijian').find('.time-check').siblings('img:nth-of-type(2)').hide();
            $(this).siblings('i').removeClass('f_col3');
            $(this).parents('.fuwushijian').find('.time-check').siblings('i').removeClass('f_col3');
        }
    });
    /*服务时间弹框单选的*/
    $('.fwsj_oneTime>input').click(function(){
        var ones = $(this).closest(".fuwushijian").find(".oCheck");
        var oneC = $(this).closest(".fuwushijian").find(".oCheck:checked");
        var alls = $(this).closest(".fuwushijian").find(".allCheck");
        if(ones.length==oneC.length){
            alls.prop('checked',true);
            alls.siblings('img:nth-of-type(1)').hide();
            alls.siblings('img:nth-of-type(2)').show();
            alls.addClass('f_col3').parent().siblings('.addhg_sel').children('i').removeClass('f_col3');
            alls.siblings('i').addClass('f_col3').parent().siblings('.addhg_sel').children('i').removeClass('f_col3');
        }else{
            alls.prop('checked',false);
            alls.siblings('img:nth-of-type(2)').hide();
            alls.siblings('img:nth-of-type(1)').show();
            alls.siblings('i').removeClass('f_col3');
        }
        if($(this).prop('checked')==true){
            $(this).siblings('img:nth-of-type(1)').hide();
            $(this).siblings('img:nth-of-type(2)').show();
            $(this).siblings('i').addClass('f_col3').parent().siblings('.addhg_sel').children('i').removeClass('f_col3');
        }else{
            $(this).siblings('img:nth-of-type(2)').hide();
            $(this).siblings('img:nth-of-type(1)').show();
            $(this).siblings('i').removeClass('f_col3');
        }
    });

    /*服务项目全选的*/
    $('.fwxm_allTime>input').click(function(){
        if($(this).prop('checked')==true){
            $(this).parents('.fuwuxianmu').find('.time-check').prop('checked',true);
            $(this).parents('.fuwuxianmu').find('.time-check').siblings('img:nth-of-type(1)').hide();
            $(this).parents('.fuwuxianmu').find('.time-check').siblings('img:nth-of-type(2)').show();
            $(this).siblings('i').addClass('f_col3');
            $(this).parents('.fuwuxianmu').find('.time-check').siblings('i').addClass('f_col3');
        }else{
            $(this).parents('.fuwuxianmu').find('.time-check').prop('checked',false);
            $(this).parents('.fuwuxianmu').find('.time-check').siblings('img:nth-of-type(1)').show();
            $(this).parents('.fuwuxianmu').find('.time-check').siblings('img:nth-of-type(2)').hide();
            $(this).siblings('i').removeClass('f_col3');
            $(this).parents('.fuwuxianmu').find('.time-check').siblings('i').removeClass('f_col3');
        }
    });
    /*服务项目单选的*/
    $('.fwxm_oneTime>input').click(function(){
        var ones = $(this).closest(".fuwuxianmu").find(".oCheck");
        var oneC = $(this).closest(".fuwuxianmu").find(".oCheck:checked");
        var alls = $(this).closest(".fuwuxianmu").find(".allCheck");
        if(ones.length==oneC.length){
            alls.prop('checked',true);
            alls.siblings('img:nth-of-type(1)').hide();
            alls.siblings('img:nth-of-type(2)').show();
            alls.siblings('i').addClass('f_col3');
        }else{
            alls.prop('checked',false);
            alls.siblings('img:nth-of-type(2)').hide();
            alls.siblings('img:nth-of-type(1)').show();
            alls.siblings('i').removeClass('f_col3');
        }
        if($(this).prop('checked')==true){
            $(this).siblings('img:nth-of-type(1)').hide();
            $(this).siblings('img:nth-of-type(2)').show();
            $(this).siblings('i').addClass('f_col3');
        }else{
            $(this).siblings('img:nth-of-type(2)').hide();
            $(this).siblings('img:nth-of-type(1)').show();
            $(this).siblings('i').removeClass('f_col3');
        }
    });
    $('.sel_current').children('input[type="checkbox"]').prop('checked',true);
    $('.sel_current').children('input[type="checkbox"]').siblings('i').removeClass('f_col3');
    $('.sel_current').children('img:nth-of-type(1)').hide();
    $('.sel_current').children('img:nth-of-type(2)').show();


});
