/**
 * Created by Wu on 2016/9/7.
 */
$(function(){
    /******养老机构*****/
    //分类筛选选中状态
    $('.jgylArea>li').click(function(){
        $(this).addClass('bgColorGreen2').siblings().removeClass('bgColorGreen2');
    });
    //分类筛选的里面类型收缩张开
    $('.screenCondition').click(function(){
        var downPic=$(this).find('.sel_up').children('img');
        if(downPic.attr("src")=="../img/w97.png"){
            $(this).next().hide();
            downPic.attr("src","../img/w98.png");
        }else{
            $(this).next().show();
            downPic.attr("src","../img/w97.png");
        }
    });
    /******养老机构详情******/
    //收藏按钮
    $('.yljg_scPic').click(function(){
        var scPic=$(this).children('span').children();
        if(scPic.attr('src')=="../img/w45.png"){
            scPic.attr('src','../img/w45_1.png');
            $(this).children('p').text('已收藏');
        }else{
            scPic.attr('src','../img/w45.png');
            $(this).children('p').text('立即收藏');
        }
    });
    /*********确认付款（养老机构）**********/
    $('.payment_wx>input[type="checkbox"]').click(function(){
        if($(this).prop('checked')==true){
            $(this).siblings('img:nth-of-type(1)').hide();
            $(this).siblings('img:nth-of-type(2)').show();
            $(this).parent().next().children('input[type="checkbox"]').prop('checked',false);
            $(this).parent().next().children('img:nth-of-type(1)').show();
            $(this).parent().next().children('img:nth-of-type(2)').hide();
        }else{
            $(this).siblings('img:nth-of-type(1)').show();
            $(this).siblings('img:nth-of-type(2)').hide();
        }
    });
    $('.payment_zfb>input[type="checkbox"]').click(function(){
        if($(this).prop('checked')==true){
            $(this).siblings('img:nth-of-type(1)').hide();
            $(this).siblings('img:nth-of-type(2)').show();
            $(this).parent().prev().children('input[type="checkbox"]').prop('checked',false);
            $(this).parent().prev().children('img:nth-of-type(1)').show();
            $(this).parent().prev().children('img:nth-of-type(2)').hide();
        }else{
            $(this).siblings('img:nth-of-type(1)').show();
            $(this).siblings('img:nth-of-type(2)').hide();
        }
    });
    /********居家护理*********/
    $('.jjhl_select_fwlx>.jgylArea>li').click(function(){
        $(this).addClass('bgColorGreen2').siblings().removeClass('bgColorGreen2');
        $(this).parent().siblings('.jgylArea').children().removeClass('bgColorGreen2');
    });
    $('.jjhl_allService>a').click(function(){
        $(this).addClass('s_current').siblings().removeClass('s_current');
        $(this).parent().next().children().eq($(this).index()).show().siblings().hide();
    });
    $('.joinCollect').click(function(){
        if($(this).text()=="加入收藏"){
            $(this).text('已收藏');
        }else{
            $(this).text('加入收藏');
        }
    });
    /********居家护理-规格选择******/
    $('.short-term').click(function(){
        $('.serviceDate').children('span:nth-of-type(2)').hide();
        $('.jjhlDateB').hide();
        $('.jjhlDateB+input').hide();
        $('.jjhlDateSelect>input:nth-of-type(1)').css({
            'width':'100%',
            'background-position':'98%,center'
        });
    });
    $('.long-term').click(function(){
        $('.serviceDate').children('span:nth-of-type(2)').show();
        $('.jjhlDateB').css('display','block');
        $('.jjhlDateB+input').css('display','block');
        $('.jjhlDateSelect>input:nth-of-type(1)').css({
            'width':'45%',
            'background-position':'95%,center'
        });
    });
});
